Feature("User-Login_Negative")

Scenario("User-Login_dengan_valid_username_dan_invalid_password", async ({ I }) => {
    I.amOnPage("")
    I.fillField("#user-name", "standard_user")
    I.fillField("#password", "secret_sauce1")
    I.click("#login-button")
    I.see("Epic sadface: Username and password do not match any user in this service")
    I.refreshPage()
})    
Scenario("User-Login_dengan_valid_username_dan_blank_password", async ({ I }) => {
    I.amOnPage("")    
    I.fillField("#user-name", "standard_user")
    I.fillField("#password", "")
    I.click("#login-button")
    I.see("Epic sadface: Password is required")
    I.refreshPage()
})
Scenario("User-Login_dengan_invalid_username_dan_valid_password", async ({ I }) => {
    I.amOnPage("")    
    I.fillField("#user-name", "standard_user1")
    I.fillField("#password", "secret_sauce")
    I.click("#login-button")
    I.see("Epic sadface: Username and password do not match any user in this service")
    I.refreshPage()
})
Scenario("User-Login_dengan_blank_username_dan_valid_password", async ({ I }) => {
    I.amOnPage("")    
    I.fillField("#user-name", "")
    I.fillField("#password", "secret_sauce")
    I.click("#login-button")
    I.see("Epic sadface: Username is required")
    I.refreshPage()
})
Scenario("User-Login_dengan_blank_username_dan_blank_password", async ({ I }) => {
    I.amOnPage("")    
    I.fillField("#user-name", "")
    I.fillField("#password", "")
    I.click("#login-button")
    I.see("Epic sadface: Username is required")
    I.refreshPage()
})
Scenario("User-Login_locked_out_user", async ({ I }) => {
    I.amOnPage("")    
    I.fillField("#user-name", "locked_out_user")
    I.fillField("#password", "secret_sauce")
    I.click("#login-button")
    I.see("Epic sadface: Sorry, this user has been locked out.")
    I.refreshPage()
})
Scenario("User-Login_problem_user", async ({ I }) => {
    I.amOnPage("")    
    I.fillField("#user-name", "problem_user")
    I.fillField("#password", "secret_sauce")
    I.click("#login-button")
    I.click("#react-burger-menu-btn")
    I.waitForElement("#logout_sidebar_link", 60)
    I.click("#logout_sidebar_link")
    I.refreshPage()
})